export const ADD_TODO = 'ADD_TODO';
export const GET_INPUT_VALUE = 'GET_INPUT_VALUE';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const USER_SELECTED = 'USER_SELECTED';

export const DISPLAY_TODOS = 'DISPLAY_TODOS';
export const TODO_FILTER = {
    SHOW_ALL_TODOS: 'SHOW_ALL_TODOS',
    SHOW_COMPLETED_TODOS: 'SHOW_COMPLETED_TODOS',
    SHOW_INCOMPLETED_TODOS: 'SHOW_INCOMPLETED_TODOS',
}
